# Melvin o7 Brain File
# This file IS the brain - patterns, edges, and learned state
# Generated by melvin.c interpreter

# Patterns (learned sequences with predictions)
pattern "ca" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:0.7500
pattern "at" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:0.7500
pattern "_at" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:18.4765
pattern "tc" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:1.1056
pattern "_tc" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:17.4823
pattern "_ca" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:17.4823

# Edges (learned connections)
edge 'a' -> 't' weight:0.4098
edge 'a' -> 'c' weight:0.2817
edge 'a' -> 's' weight:0.3085
edge 'c' -> 'a' weight:0.3954
edge 'c' -> 't' weight:0.6045
edge 's' -> 'a' weight:0.3612
edge 's' -> 't' weight:0.6365
edge 't' -> 'a' weight:0.2588
edge 't' -> 'c' weight:0.3291
edge 't' -> 's' weight:0.4120

# System state
state error_rate:0.7507 learning_rate:0.3251 pattern_count:6
