# Melvin o7 Brain File
# This file IS the brain - patterns, edges, and learned state
# Generated by melvin.c interpreter

# Patterns (learned sequences with predictions)
pattern "ca" -> "tg" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:1.3600 utility:1.0000 port_in:0 port_out:0
pattern "tc" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:1.1056 port_in:0 port_out:0
pattern "_tc" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:24.8446 port_in:0 port_out:0
pattern "_ca" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:24.8832 port_in:0 port_out:0
pattern "tb" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:0.8708 port_in:0 port_out:0
pattern "ba" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:0.8708 port_in:0 port_out:0
pattern "_tb" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:12.4876 port_in:0 port_out:0
pattern "_ba" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:12.4876 port_in:0 port_out:0
pattern "td" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:0.8523 port_in:0 port_out:0
pattern "do" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:0.8523 port_in:0 port_out:0
pattern "og" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:0.8523 port_in:0 port_out:0
pattern "_td" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:1.3906 port_in:0 port_out:0
pattern "_do" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:5.9109 port_in:0 port_out:0
pattern "_og" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:5.9109 port_in:0 port_out:0
pattern "gd" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:1.3104 port_in:0 port_out:0
pattern "_gd" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:5.3604 port_in:0 port_out:0
pattern "gc" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:2.0758 port_in:0 port_out:0
pattern "_gc" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:0.9392 port_in:0 port_out:0
pattern "tr" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:0.9392 port_in:0 port_out:0
pattern "ra" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:1.8088 port_in:0 port_out:0
pattern "_tr" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:1.2913 port_in:0 port_out:0
pattern "_ra" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:1.2913 port_in:0 port_out:0
pattern "th" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:0.9392 port_in:0 port_out:0
pattern "ha" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:1.8088 port_in:0 port_out:0
pattern "_th" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:2.8208 port_in:0 port_out:0
pattern "_ha" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:2.8208 port_in:0 port_out:0

# Pattern-to-pattern edges
pat_edge 0 -> 3 weight:1.0000
pat_edge 0 -> 5 weight:1.0000
pat_edge 0 -> 4 weight:1.0000
pat_edge 0 -> 7 weight:1.0000
pat_edge 0 -> 6 weight:1.0000
pat_edge 0 -> 1 weight:1.0000
pat_edge 0 -> 9 weight:0.9170
pat_edge 0 -> 11 weight:0.9999
pat_edge 0 -> 16 weight:0.9999
pat_edge 0 -> 15 weight:1.0000
pat_edge 0 -> 12 weight:0.4472
pat_edge 1 -> 0 weight:1.0000
pat_edge 1 -> 3 weight:1.0000
pat_edge 1 -> 4 weight:0.9990
pat_edge 1 -> 5 weight:0.9995
pat_edge 1 -> 6 weight:1.0000
pat_edge 1 -> 7 weight:1.0000
pat_edge 1 -> 9 weight:0.9170
pat_edge 1 -> 11 weight:0.9998
pat_edge 1 -> 16 weight:0.9998
pat_edge 1 -> 15 weight:1.0000
pat_edge 3 -> 0 weight:1.0000
pat_edge 3 -> 5 weight:1.0000
pat_edge 3 -> 4 weight:1.0000
pat_edge 3 -> 7 weight:1.0000
pat_edge 3 -> 6 weight:1.0000
pat_edge 3 -> 1 weight:1.0000
pat_edge 3 -> 9 weight:0.9170
pat_edge 3 -> 11 weight:0.9999
pat_edge 3 -> 16 weight:0.9999
pat_edge 3 -> 15 weight:1.0000
pat_edge 3 -> 12 weight:0.4472
pat_edge 3 -> 18 weight:0.9979
pat_edge 3 -> 25 weight:0.6394
pat_edge 4 -> 0 weight:1.0000
pat_edge 4 -> 3 weight:1.0000
pat_edge 4 -> 5 weight:1.0000
pat_edge 4 -> 7 weight:1.0000
pat_edge 4 -> 6 weight:1.0000
pat_edge 4 -> 1 weight:0.9990
pat_edge 4 -> 9 weight:0.6088
pat_edge 4 -> 11 weight:0.4198
pat_edge 4 -> 16 weight:0.4198
pat_edge 4 -> 18 weight:0.9979
pat_edge 4 -> 25 weight:0.6394
pat_edge 5 -> 3 weight:1.0000
pat_edge 5 -> 0 weight:1.0000
pat_edge 5 -> 4 weight:1.0000
pat_edge 5 -> 7 weight:1.0000
pat_edge 5 -> 6 weight:1.0000
pat_edge 5 -> 1 weight:0.9995
pat_edge 5 -> 9 weight:0.6088
pat_edge 5 -> 11 weight:0.4198
pat_edge 5 -> 16 weight:0.4198
pat_edge 6 -> 0 weight:1.0000
pat_edge 6 -> 3 weight:1.0000
pat_edge 6 -> 4 weight:1.0000
pat_edge 6 -> 5 weight:1.0000
pat_edge 6 -> 7 weight:1.0000
pat_edge 6 -> 1 weight:1.0000
pat_edge 6 -> 11 weight:0.9999
pat_edge 6 -> 16 weight:0.9999
pat_edge 6 -> 15 weight:0.9995
pat_edge 6 -> 12 weight:0.4472
pat_edge 6 -> 18 weight:0.9979
pat_edge 6 -> 25 weight:0.6394
pat_edge 7 -> 0 weight:1.0000
pat_edge 7 -> 3 weight:1.0000
pat_edge 7 -> 4 weight:1.0000
pat_edge 7 -> 5 weight:1.0000
pat_edge 7 -> 6 weight:1.0000
pat_edge 7 -> 1 weight:1.0000
pat_edge 7 -> 11 weight:0.9999
pat_edge 7 -> 16 weight:0.9999
pat_edge 7 -> 15 weight:0.9995
pat_edge 7 -> 12 weight:0.4472
pat_edge 9 -> 0 weight:0.9170
pat_edge 9 -> 1 weight:0.9170
pat_edge 9 -> 3 weight:0.9170
pat_edge 9 -> 4 weight:0.6088
pat_edge 9 -> 5 weight:0.6088
pat_edge 9 -> 15 weight:0.6798
pat_edge 11 -> 0 weight:0.9999
pat_edge 11 -> 1 weight:0.9998
pat_edge 11 -> 3 weight:0.9999
pat_edge 11 -> 4 weight:0.4198
pat_edge 11 -> 5 weight:0.4198
pat_edge 11 -> 6 weight:0.9999
pat_edge 11 -> 7 weight:0.9999
pat_edge 11 -> 16 weight:0.9999
pat_edge 11 -> 15 weight:0.9995
pat_edge 11 -> 12 weight:0.4472
pat_edge 12 -> 0 weight:0.4472
pat_edge 12 -> 3 weight:0.4472
pat_edge 12 -> 6 weight:0.4472
pat_edge 12 -> 7 weight:0.4472
pat_edge 12 -> 11 weight:0.4472
pat_edge 12 -> 15 weight:0.4472
pat_edge 12 -> 16 weight:0.4472
pat_edge 15 -> 0 weight:1.0000
pat_edge 15 -> 1 weight:1.0000
pat_edge 15 -> 3 weight:1.0000
pat_edge 15 -> 6 weight:0.9995
pat_edge 15 -> 7 weight:0.9995
pat_edge 15 -> 11 weight:0.9995
pat_edge 15 -> 16 weight:0.9995
pat_edge 15 -> 9 weight:0.6798
pat_edge 15 -> 12 weight:0.4472
pat_edge 16 -> 0 weight:0.9999
pat_edge 16 -> 1 weight:0.9998
pat_edge 16 -> 3 weight:0.9999
pat_edge 16 -> 4 weight:0.4198
pat_edge 16 -> 5 weight:0.4198
pat_edge 16 -> 6 weight:0.9999
pat_edge 16 -> 7 weight:0.9999
pat_edge 16 -> 11 weight:0.9999
pat_edge 16 -> 15 weight:0.9995
pat_edge 16 -> 12 weight:0.4472
pat_edge 18 -> 3 weight:0.9979
pat_edge 18 -> 4 weight:0.9979
pat_edge 18 -> 6 weight:0.9979
pat_edge 24 -> 25 weight:0.9756
pat_edge 25 -> 3 weight:0.6394
pat_edge 25 -> 4 weight:0.6394
pat_edge 25 -> 6 weight:0.6394
pat_edge 25 -> 24 weight:0.9756

# Node edges (learned connections)
edge 'a' -> 't' weight:0.1717
edge 'a' -> 's' weight:0.1604
edge 'a' -> 'g' weight:0.1057
edge 'a' -> 'o' weight:0.1107
edge 'a' -> 'r' weight:0.1075
edge 'a' -> 'h' weight:0.1360
edge 'b' -> 'a' weight:0.1629
edge 'b' -> 'o' weight:0.1054
edge 'b' -> 's' weight:0.5645
edge 'c' -> 't' weight:0.2593
edge 'c' -> 'a' weight:0.1774
edge 'c' -> 'o' weight:0.1805
edge 'c' -> 's' weight:0.2351
edge 'd' -> 'o' weight:0.3735
edge 'd' -> 'a' weight:0.1696
edge 'd' -> 's' weight:0.3831
edge 'g' -> 'o' weight:0.3363
edge 'g' -> 'a' weight:0.1828
edge 'g' -> 's' weight:0.3492
edge 'h' -> 'a' weight:0.3968
edge 'h' -> 's' weight:0.4891
edge 'o' -> 'g' weight:0.1663
edge 'o' -> 'd' weight:0.1599
edge 'o' -> 's' weight:0.1730
edge 'o' -> 't' weight:0.1565
edge 'r' -> 'a' weight:0.2764
edge 'r' -> 'o' weight:0.1655
edge 'r' -> 's' weight:0.5116
edge 's' -> 't' weight:0.1349
edge 's' -> 'g' weight:0.1245
edge 's' -> 'b' weight:0.1178
edge 's' -> 'd' weight:0.1219
edge 's' -> 'o' weight:0.1298
edge 's' -> 'r' weight:0.1115
edge 's' -> 'h' weight:0.1185
edge 't' -> 'c' weight:0.2269
edge 't' -> 's' weight:0.3505
edge 't' -> 'a' weight:0.1469
edge 't' -> 'o' weight:0.2330

# System state
state error_rate:0.6970 learning_rate:0.2429 pattern_count:28
