# Melvin o7 Brain File
# This file IS the brain - patterns, edges, and learned state
# Generated by melvin.c interpreter

# Patterns (learned sequences with predictions)
pattern "ca" -> "t" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:0.7500 utility:3.1000 port_in:0 port_out:0
pattern "tc" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:1.1056 port_in:0 port_out:0
pattern "_tc" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:6.2944 port_in:0 port_out:0
pattern "_ca" context:[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000] strength:6.2944 port_in:0 port_out:0

# Pattern-to-pattern edges
pat_edge 0 -> 3 weight:0.9995
pat_edge 0 -> 5 weight:0.9807
pat_edge 0 -> 4 weight:0.8242
pat_edge 3 -> 0 weight:0.9995
pat_edge 3 -> 5 weight:1.0000
pat_edge 3 -> 4 weight:0.9997
pat_edge 4 -> 0 weight:0.8242
pat_edge 4 -> 3 weight:0.9997
pat_edge 4 -> 5 weight:0.9992
pat_edge 5 -> 3 weight:1.0000
pat_edge 5 -> 0 weight:0.9807
pat_edge 5 -> 4 weight:0.9992

# Node edges (learned connections)
edge 'a' -> 't' weight:0.5134
edge 'a' -> 's' weight:0.4066
edge 'c' -> 'a' weight:0.1882
edge 'c' -> 't' weight:0.4281
edge 'c' -> 's' weight:0.3837
edge 's' -> 'a' weight:0.2858
edge 's' -> 'c' weight:0.3294
edge 's' -> 't' weight:0.3848
edge 't' -> 'a' weight:0.2754
edge 't' -> 'c' weight:0.3101
edge 't' -> 's' weight:0.4145

# System state
state error_rate:0.7416 learning_rate:0.2953 pattern_count:6
